# Generated by Django 5.1.6 on 2025-03-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='imgage',
            new_name='image',
        ),
    ]
