# Generated by Django 5.1.6 on 2025-03-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_imgage',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quality',
            new_name='quantity',
        ),
    ]
